npm install -D @types/hoist-non-react-statics
The following error occured with the `tsc` execution without webpack)
```
npm run typecheck

> tower-offense-7x7@0.0.0 typecheck /Users/ishii.koujirou/app/tower-offense-7x7
> $(npm bin)/tsc --project tsconfig-typecheck.json

node_modules/react-dnd/lib/cjs/interfaces/classApi.d.ts:5:33 - error TS7016: Could not find a declaration file for module 'hoist-non-react-statics'. '/Users/ishii.koujirou/app/tower-offense-7x7/node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js' implicitly has an 'any' type.
  Try `npm install @types/hoist-non-react-statics` if it exists or add a new declaration (.d.ts) file containing `declare module 'hoist-non-react-statics';`

  5 import { NonReactStatics } from 'hoist-non-react-statics';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~

                                    Found 1 error.
```

I have not investigated the cause...